In [1]:
import numpy as np
import pandas as pd
import torch
from rdkit import Chem
from sklearn import model_selection as sk_modelselection
from torch.nn import functional as F
from torch.utils.data import DataLoader, Dataset

from graphmodels import constants, datasets

device = "cpu"
if torch.cuda.is_available():
    print("GPU is available")
    device = "cuda"
else:
    print("Running on CPU")

GPU is available


# Load data

In [2]:
sol_df = pd.read_csv("../datasets/chemistry/delaney-processed.csv")

In [15]:
sol_df["mol"] = sol_df["smiles"].apply(Chem.MolFromSmiles)
sol_df["num_atoms"] = sol_df["mol"].apply(lambda x : x.GetNumAtoms())
MAX_NUM_ATOMS = sol_df["num_atoms"].max()
print(f"Max num atoms = {MAX_NUM_ATOMS}")

Max num atoms = 55


In [4]:
# Split data
train_df, test_df = sk_modelselection.train_test_split(sol_df, test_size=0.2, random_state=42, shuffle=True)
train_df, valid_df = sk_modelselection.train_test_split(train_df, test_size=0.15, random_state=42, shuffle=True)

In [5]:
train_df.shape, test_df.shape, valid_df.shape

((766, 11), (226, 11), (136, 11))

In [6]:
train_df

Compound ID  ESOL predicted log solubility in mols per litre   
456             Etomidate                                           -3.359  \
938            isoguanine                                           -1.740   
925                 RTI 6                                           -3.335   
810      Tetrahydropyran                                            -0.978   
495             Minoxidil                                           -1.809   
..                    ...                                              ...   
837             Metoxuron                                           -2.683   
587             benodanil                                           -4.245   
776  1-Methylcyclohexene                                            -2.574   
153       1-Chloropentane                                           -2.294   
29       Methyl octanoate                                           -2.608   

     Minimum Degree  Molecular Weight  Number of H-Bond Donors   
456               1           244.294                        0  \
938               1           151.129                        3   
925               1           313.361                        2   
810               2            86.134                        0   
495               1           209.253                        2   
..              ...               ...                      ...   
837               1           228.679                        1   
587               1           323.133                        1   
776               1            96.173                        0   
153               1           106.596                        0   
29                1           158.241                        0   

     Number of Rings  Number of Rotatable Bonds  Polar Surface Area   
456                2                          4               44.12  \
938                2                          0              100.71   
925                3                          4               81.59   
810                1                          0                9.23   
495                2                          1               95.11   
..               ...                        ...                 ...   
837                1                          2               41.57   
587                2                          2               29.10   
776                1                          0                0.00   
153                0                          3                0.00   
29                 0                          6               26.30   

     measured log solubility in mols per litre   
456                                     -4.735  \
938                                     -3.401   
925                                     -3.360   
810                                     -0.030   
495                                     -1.989   
..                                         ...   
837                                     -2.564   
587                                     -4.210   
776                                     -3.270   
153                                     -2.730   
29                                      -3.170   

                                      smiles   
456              CCOC(=O)c1cncn1C(C)c2ccccc2  \
938                    Nc1nc(O)nc2nc[nH]c12    
925  CCN2c1nc(N(C)(CCO))ccc1NC(=O)c3cccnc23    
810                                 C1CCOCC1   
495                Nc1cc(nc(N)n1=O)N2CCCCC2    
..                                       ...   
837                COc1ccc(NC(=O)N(C)C)cc1Cl   
587              c1c(NC(=O)c2ccccc2(I))cccc1   
776                               CC1=CCCCC1   
153                                  CCCCCCl   
29                            CCCCCCCC(=O)OC   

                                                  mol  
456  <rdkit.Chem.rdchem.Mol object at 0x7f03de9299a0>  
938  <rdkit.Chem.rdchem.Mol object at 0x7f03de936c70>  
925  <rdkit.Chem.rdchem.Mol object at 0x7f03de9366c0>  
810  <rdkit.Chem.rdchem.Mol o

# Create datasets

In [10]:
train_dset = datasets.NeuralFingerprintDataset(smiles=tuple(train_df["smiles"]),
                                               targets=tuple(train_df["measured log solubility in mols per litre"]))

In [11]:
first_elem = train_dset[0]

In [12]:
(atom_feats, bond_feats, adj_matrix), target = first_elem

In [16]:
atom_feats.shape, bond_feats.shape, adj_matrix.shape

(torch.Size([18, 136]), torch.Size([18, 18, 24]), torch.Size([18, 18]))

In [91]:
x = torch.rand(3,4)
z = torch.rand(3,3)
y = torch.rand((3,3,4))
z

tensor([[0.9465, 0.9977, 0.5313],
        [0.9555, 0.4389, 0.3831],
        [0.1504, 0.6180, 0.2469]])

In [95]:
F.pad(z, pad=(0,1,0,1)).shape

torch.Size([4, 4])

In [38]:
num_to_pad = MAX_NUM_ATOMS - atom_feats.shape[0]
num_to_pad

37

In [51]:
atom_feats.size()[0]

18

In [96]:
atom_feats_padded = F.pad(atom_feats, pad=(0,0,0,num_to_pad), value=0)

bond_feats_padded = F.pad(bond_feats, pad=(0,0,0,num_to_pad,0,num_to_pad), value=0)

adj_matrix_padded = F.pad(adj_matrix, pad=(0,num_to_pad,0,num_to_pad), value=0)

In [98]:
adj_matrix_padded

tensor([[0., 1., 0.,  ..., 0., 0., 0.],
        [1., 0., 1.,  ..., 0., 0., 0.],
        [0., 1., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])

In [136]:
def neuralgraph_collate(batch, max_num_atoms: int):
    all_atom_features = []
    all_bond_features = []
    all_adj_matrices = []

    # Get max number of atoms in data
    for feats in batch:
        print(feats)
    #     atom_feats, bond_feats, adj_matrix = feats
    #     num_to_pad = max_num_atoms - atom_feats.shape[0]
    #     atom_feats_padded = F.pad(atom_feats, pad=(0,0,0,num_to_pad), value=0)
    #     bond_feats_padded = F.pad(bond_feats, pad=(0,0,0,num_to_pad,0,num_to_pad), value=0)
    #     adj_matrix_padded = F.pad(adj_matrix, pad=(0,num_to_pad,0,num_to_pad), value=0)

    #     all_bond_features.append(bond_feats_padded)
    #     all_adj_matrices.append(adj_matrix_padded)
    #     all_atom_features.append(atom_feats_padded)
    # return tuple(map(torch.stack, [all_atom_features, all_bond_features, all_adj_matrices]))

In [137]:
from functools import partial

In [138]:
ff = partial(neuralgraph_collate, max_num_atoms=MAX_NUM_ATOMS)

In [139]:
len(first_elem)

2

In [140]:
ff(first_elem)

(tensor([[0., 0., 0.,  ..., 1., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 1.],
        [0., 0., 0.,  ..., 0., 0., 1.],
        [0., 0., 0.,  ..., 0., 0., 1.]]), tensor([[[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 1., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        [[0., 1., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 1., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        [[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 1., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
 